export const SCOPES = {
    CREATE_TENANT: 'create_tenant',
    VIEW_TENANT: 'view_tenant',
    VIEW_USERS: 'view_users',
    CREATE_ADMIN_USER: 'create_admin_user',
    CREATE_TEAM: 'create_team',
    CREATE_ENGAGEMENT: 'create_engagement',
    EDIT_ENGAGEMENT: 'edit_engagement',
    EDIT_DRAFT_ENGAGEMENT: 'edit_draft_engagement',
    CREATE_SURVEY: 'create_survey',
    PUBLISH_ENGAGMENT: 'publish_engagement',
    VIEW_ENGAGEMENT: 'view_engagement',
    VIEW_PRIVATE_ENGAGMENTS: 'view_private_engagements',
    VIEW_ASSIGNED_ENGAGEMENTS: 'view_assigned_engagements',
    REVIEW_COMMENTS: 'review_comments',
    ACCESS_DASHBOARD: 'access_dashboard',
    VIEW_MEMBERS: 'view_members',
    EDIT_MEMBERS: 'edit_members',
    APP_ADMIN: 'app-admin',
    VIEW_SURVEYS: 'view_surveys',
    VIEW_FEEDBACKS: 'view_feedbacks',
};
