version: "3.5"
services:
  engagement-db:
    container_name: engagement-db
    image: postgres:14
    command: postgres -c 'max_connections=500'
    ports:
      - "5432:5432"
    env_file:
      - ./postgres.env
    restart: unless-stopped
    networks:
      - depnetwork
    volumes:
      - ./backups:/backups
      - ./scripts:/scripts
      - engagement-db:/var/lib/postgresql/data
      - ./init://docker-entrypoint-initdb.d
volumes:
  engagement-db:
    name: engagement-db.local
networks:
  depnetwork:
    name: depnetwork