"""add_runcycle_id_to_all_tables

Revision ID: 05e82fada6fe
Revises: e62ba34dc486
Create Date: 2022-10-06 11:54:03.453343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05e82fada6fe'
down_revision = 'e62ba34dc486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('request_type_option', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('request_type_radio', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('request_type_selectbox', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('request_type_textarea', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('request_type_textfield', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('response_type_option', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('response_type_radio', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('response_type_selectbox', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('response_type_textarea', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('response_type_textfield', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('survey', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('user_details', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('user_feedback', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    op.add_column('user_response_detail', sa.Column('runcycle_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_response_detail', 'runcycle_id')
    op.drop_column('user_feedback', 'runcycle_id')
    op.drop_column('user_details', 'runcycle_id')
    op.drop_column('survey', 'runcycle_id')
    op.drop_column('response_type_textfield', 'runcycle_id')
    op.drop_column('response_type_textarea', 'runcycle_id')
    op.drop_column('response_type_selectbox', 'runcycle_id')
    op.drop_column('response_type_radio', 'runcycle_id')
    op.drop_column('response_type_option', 'runcycle_id')
    op.drop_column('request_type_textfield', 'runcycle_id')
    op.drop_column('request_type_textarea', 'runcycle_id')
    op.drop_column('request_type_selectbox', 'runcycle_id')
    op.drop_column('request_type_radio', 'runcycle_id')
    op.drop_column('request_type_option', 'runcycle_id')
    op.drop_column('engagement', 'runcycle_id')
    # ### end Alembic commands ###
