"""alter_request_id

Revision ID: 212a192b20ec
Revises: fd7e79bbc57a
Create Date: 2023-06-25 20:41:27.152970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212a192b20ec'
down_revision = 'fd7e79bbc57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_type_option', 'request_id',
               existing_type=sa.String(length=20),
               type_=sa.String(length=250))
    op.alter_column('response_type_option', 'request_id',
               existing_type=sa.String(length=20),
               type_=sa.String(length=250))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_type_option', 'request_id',
               existing_type=sa.String(length=250),
               type_=sa.String(length=20))
    op.alter_column('response_type_option', 'request_id',
               existing_type=sa.String(length=250),
               type_=sa.String(length=20))
    # ### end Alembic commands ###
