"""add_email_verification

Revision ID: 4da03ace3157
Revises: 05e82fada6fe
Create Date: 2023-05-01 14:28:32.941204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da03ace3157'
down_revision = '05e82fada6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('runcycle_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_email_ver_id', sa.Integer(), nullable=True, comment='Source System Id.'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('engagement_id', sa.Integer(), nullable=True, comment='Source System Engagement Id.'),
    sa.Column('survey_id', sa.Integer(), nullable=True, comment='Source System Survey Id.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('engagement', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('engagement', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('engagement', sa.Column('geojson', sa.Text(), nullable=True))
    op.add_column('engagement', sa.Column('marker_label', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement', 'marker_label')
    op.drop_column('engagement', 'geojson')
    op.drop_column('engagement', 'longitude')
    op.drop_column('engagement', 'latitude')
    op.drop_table('email_verification')
    # ### end Alembic commands ###
