"""updating_key_column_length

Revision ID: 4f1a2c9776b9
Revises: da8a6ba28564
Create Date: 2023-06-30 22:27:07.600495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1a2c9776b9'
down_revision = 'da8a6ba28564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_type_option', 'key',
               existing_type=sa.String(length=100),
               type_=sa.String(length=250))
    op.alter_column('response_type_option', 'request_key',
               existing_type=sa.String(length=100),
               type_=sa.String(length=250))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_type_option', 'key',
               existing_type=sa.String(length=250),
               type_=sa.String(length=100))
    op.alter_column('response_type_option', 'request_key',
               existing_type=sa.String(length=250),
               type_=sa.String(length=100))
    # ### end Alembic commands ###
