"""alter_position_column_name

Revision ID: 88c01f327bed
Revises: 4f1a2c9776b9
Create Date: 2023-07-05 10:30:01.803632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c01f327bed'
down_revision = '4f1a2c9776b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_type_option', sa.Column('position', sa.Integer(), nullable=True))
    op.drop_column('request_type_option', 'postion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_type_option', sa.Column('postion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('request_type_option', 'position')
    # ### end Alembic commands ###
