"""adding_flag_columns

Revision ID: da8a6ba28564
Revises: 212a192b20ec
Create Date: 2023-06-28 18:15:04.605837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8a6ba28564'
down_revision = '212a192b20ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_type_option', sa.Column('display', sa.Boolean(), nullable=True))
    op.execute('UPDATE request_type_option SET display = True')
    op.add_column('survey', sa.Column('generate_dashboard', sa.Boolean(), nullable=True))
    op.execute('UPDATE survey SET generate_dashboard = True')
    op.drop_table('request_type_radio')
    op.drop_table('request_type_selectbox')
    op.drop_table('request_type_textarea')
    op.drop_table('request_type_textfield')
    op.drop_table('response_type_radio')
    op.drop_table('response_type_selectbox')
    op.drop_table('response_type_textarea')
    op.drop_table('response_type_textfield')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'generate_dashboard')
    op.drop_column('request_type_option', 'display')
    op.create_table('request_type_radio',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=200), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.Column('postion', sa.Integer(), nullable=True),
                    sa.Column('runcycle_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('request_type_selectbox',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=200), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.Column('postion', sa.Integer(), nullable=True),
                    sa.Column('runcycle_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('request_type_textarea',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=200), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.Column('postion', sa.Integer(), nullable=True),
                    sa.Column('runcycle_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('request_type_textfield',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=200), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.Column('postion', sa.Integer(), nullable=True),
                    sa.Column('runcycle_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('response_type_radio',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('request_key', sa.String(length=100), nullable=False),
                    sa.Column('value', sa.Text(), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
					sa.Column('runcycle_id', sa.Integer(), nullable=True),
					sa.Column('participant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'request_key')
                    )
    op.create_table('response_type_selectbox',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('request_key', sa.String(length=100), nullable=False),
                    sa.Column('value', sa.Text(), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
					sa.Column('runcycle_id', sa.Integer(), nullable=True),
					sa.Column('participant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'request_key')
                    )
    op.create_table('response_type_textarea',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('request_key', sa.String(length=100), nullable=False),
                    sa.Column('value', sa.Text(), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
					sa.Column('runcycle_id', sa.Integer(), nullable=True),
					sa.Column('participant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'request_key')
                    )
    op.create_table('response_type_textfield',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('request_key', sa.String(length=100), nullable=False),
                    sa.Column('value', sa.Text(), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
					sa.Column('runcycle_id', sa.Integer(), nullable=True),
					sa.Column('participant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'request_key')
                    )
    # ### end Alembic commands ###
