"""add participant

Revision ID: fd7e79bbc57a
Revises: 4da03ace3157
Create Date: 2023-06-06 10:24:28.667417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7e79bbc57a'
down_revision = '4da03ace3157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.execute('UPDATE email_verification SET participant_id = user_id;')
    op.drop_column('email_verification', 'user_id')

    op.add_column('response_type_option', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.execute('UPDATE response_type_option SET participant_id = user_id;')
    op.drop_column('response_type_option', 'user_id')

    op.add_column('response_type_radio', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.execute('UPDATE response_type_radio SET participant_id = user_id;')
    op.drop_column('response_type_radio', 'user_id')

    op.add_column('response_type_selectbox', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.execute('UPDATE response_type_selectbox SET participant_id = user_id;')
    op.drop_column('response_type_selectbox', 'user_id')

    op.add_column('response_type_textarea', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.execute('UPDATE response_type_textarea SET participant_id = user_id;')
    op.drop_column('response_type_textarea', 'user_id')

    op.add_column('response_type_textfield', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.execute('UPDATE response_type_textfield SET participant_id = user_id;')
    op.drop_column('response_type_textfield', 'user_id')

    op.add_column('user_response_detail', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.execute('UPDATE user_response_detail SET participant_id = user_id;')
    op.drop_column('user_response_detail', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_response_detail', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute('UPDATE user_response_detail SET user_id = participant_id;')
    op.drop_column('user_response_detail', 'participant_id')

    op.add_column('response_type_textfield', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute('UPDATE response_type_textfield SET user_id = participant_id;')
    op.drop_column('response_type_textfield', 'participant_id')

    op.add_column('response_type_textarea', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute('UPDATE response_type_textarea SET user_id = participant_id;')
    op.drop_column('response_type_textarea', 'participant_id')

    op.add_column('response_type_selectbox', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute('UPDATE response_type_selectbox SET user_id = participant_id;')
    op.drop_column('response_type_selectbox', 'participant_id')

    op.add_column('response_type_radio', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute('UPDATE response_type_radio SET user_id = participant_id;')
    op.drop_column('response_type_radio', 'participant_id')

    op.add_column('response_type_option', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute('UPDATE response_type_option SET user_id = participant_id;')
    op.drop_column('response_type_option', 'participant_id')

    op.add_column('email_verification', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute('UPDATE email_verification SET user_id = participant_id;')
    op.drop_column('email_verification', 'participant_id')
    # ### end Alembic commands ###
