environment: test

site:
  url: met-web-test.apps.gold.devops.gov.bc.ca

keycloak:
  baseUrl: 'test.loginproxy.gov.bc.ca'

email:
  notificationsEndpoint: 'https://met-notify-api-test.apps.gold.devops.gov.bc.ca/api/v1/notifications/email'
  environment: 'You are using the TEST environment'

image:
  tag: test

vault:
  engine: 'e903c2-nonprod'
  path: '/test'