environment: test

site:
  url: met-web-test.apps.gold.devops.gov.bc.ca

keycloak:
  baseUrl: 'test.loginproxy.gov.bc.ca'

email:
  environment: 'You are using the TEST environment'

image:
  tag: test

vault:
  engine: 'e903c2-nonprod'
  path: '/test'