environment: prod

site:
  url: met-web-demo.apps.gold.devops.gov.bc.ca

keycloak:
  baseUrl: 'loginproxy.gov.bc.ca'

email:
  notificationsEndpoint: 'https://met-notify-api.apps.gold.devops.gov.bc.ca/api/v1/notifications/email'
  environment: 'Sent from the Production environment'
  
image:
  tag: prod

vault:
  engine: 'e903c2-prod'
  path: '' # no /prod because prod is at the root of the vault