# Compiled for: {{required "Please use one of --values values_dev.yaml, --values values_test.yaml, or --values values_prod.yaml" .Values.environment }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    app-group: met-app
spec:
  replicas: {{ .Values.app.replicas }}
  revisionHistoryLimit: 10
  selector:
    app: {{ .Values.app.name }}
  strategy:
    type: Rolling
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        environment: {{ .Values.environment }}
        role: api
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/namespace: platform-services
        vault.hashicorp.com/role: {{ .Values.vault.engine }}
        vault.hashicorp.com/auth-path: auth/k8s-gold
        vault.hashicorp.com/agent-inject-secret-email: {{ .Values.vault.engine }}{{ .Values.vault.path }}/email
        # Iterate over the secret data and export each key-value pair as an environment variable
        vault.hashicorp.com/agent-inject-template-email: |
          {{`{{- with secret `}}"{{ .Values.vault.engine }}{{ .Values.vault.path }}/email"{{` }}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}='{{ $v }}'
          {{- end }}
          {{- end }}`}}
        vault.hashicorp.com/agent-inject-secret-met-jwt-oidc: {{ .Values.vault.engine }}{{ .Values.vault.path }}/jwt-oidc
        # Here we use some overrides because the client ID and secret should be
        # from met-api since it is the client here, and not met-web
        vault.hashicorp.com/agent-inject-template-met-jwt-oidc: |
          {{`{{- with secret `}}"{{ .Values.vault.engine }}{{ .Values.vault.path }}/jwt-oidc"{{` }}
          {{- range $k, $v := .Data.data }}
          {{- if eq $k "MET_ADMIN_CLIENT_ID" }}
          export JWT_OIDC_AUDIENCE='{{ $v }}'
          {{- else if eq $k "MET_ADMIN_CLIENT_SECRET" }}
          export JWT_OIDC_CLIENT_SECRET='{{ $v }}'
          {{- else }}
          export {{ $k }}='{{ $v }}'
          {{- end }}
          {{- end }}
          {{- end }}`}}
        vault.hashicorp.com/agent-inject-secret-global: {{ .Values.vault.engine }}{{ .Values.vault.path }}/global
        vault.hashicorp.com/agent-inject-template-global: |
          {{`{{- with secret `}}"{{ .Values.vault.engine }}{{ .Values.vault.path }}/global"{{` }}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}='{{ $v }}'
          {{- end }}
          {{- end }}`}}
    spec:
      # Needed to allow the vault agent to run in the pod
      serviceAccountName: {{ .Values.app.licenseplate }}-vault
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.repository }}/{{ .Values.app.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        envFrom:
        - configMapRef:
            name: {{ .Values.app.name }}
        imagePullPolicy: Always
        stdin: true
        tty: true
        command:
        - /bin/bash
        - -c
        - |
          source /vault/secrets/email && \
          source /vault/secrets/met-jwt-oidc && \
          source /vault/secrets/global && \
          bash /opt/app-root/docker-entrypoint.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30