apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    app-group: met-app
spec:
  host: {{ .Values.app.host }}
  path: {{ .Values.app.path }}
  port:
    targetPort: {{ .Values.app.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.app.name }}
    weight: 100
  wildcardPolicy: None