version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command: -b 0.0.0.0 -Djboss.http.port=8081 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/keycloak/test -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8081/auth/realms/demo || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ./setup:/tmp/keycloak/test/
  met-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD:admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 54332:5432/tcp
    restart: unless-stopped

  met-db-test:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD:admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 54333:5432/tcp
    restart: unless-stopped 
   
  met-analytics-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data4
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD:admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 54334:5432/tcp
    restart: unless-stopped        
           
  
volumes:
  db-data:
    driver: local
  