version: "3.9"

services:
  met-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD:admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 54332:5432/tcp
    restart: unless-stopped

  met-db-test:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD:admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 54333:5432/tcp
    restart: unless-stopped 
   
  met-analytics-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data4
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD:admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 54334:5432/tcp
    restart: unless-stopped        
           
  
volumes:
  db-data:
    driver: local
  