version: "3.9"

services:
  api:
    build: .
    command: flask run
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=docker
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_OIDC_AUDIENCE=met-web
      - JWT_OIDC_WELL_KNOWN_CONFIG=https://met-oidc-dev.apps.gold.devops.gov.bc.ca/auth/realms/met/.well-known/openid-configuration
      - JWT_OIDC_ALGORITHMS=RS256
      - JWT_OIDC_JWKS_URI=https://met-oidc-dev.apps.gold.devops.gov.bc.ca/auth/realms/met/protocol/openid-connect/certs
      - JWT_OIDC_ISSUER=https://met-oidc-dev.apps.gold.devops.gov.bc.ca/auth/realms/met
      - JWT_OIDC_CACHING_ENABLED=True
      - JWT_OIDC_JWKS_CACHE_TIMEOUT=300
  met-db:
    image: postgres
    container_name: met-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}