codecov:
  require_ci_to_pass: true
  branch: main
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: false
    project:
      default: false
      backend:
        target: 80%
        flags:
          - metapi
      ui:
        target: 35%
        flags:
          - metweb

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: false

flags:
  metapi:
    paths:
      - met-api/src/met_api
    carryforward: true
  metweb:
    paths:
      - met-web/src
    carryforward: true
