apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
    app-group: met-app
  name: {{ .Values.app.name }}
spec:
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.app.name }}
  sessionAffinity: None
  type: ClusterIP