---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: "{{ .Values.redash.database.password }}"
  PYTHONUNBUFFERED: "0"
  REDASH_COOKIE_SECRET: redash-selfhosted
  REDASH_DATABASE_URL: "{{ .Values.redash.database.url }}"
  REDASH_DATABASE_PASSWORD: "{{ .Values.redash.database.password }}"
  REDASH_LOG_LEVEL: INFO
  REDASH_REDIS_URL: "redis://redis-exporter:6379/0" # url of the redis database to connect to
  REDASH_SECRET_KEY: redash-selfhosted
  REDASH_MULTI_ORG: 'false'
