# Some magic to prevent us needing separate values files for each environment
{{- $namespaceParts := splitList "-" .Release.Namespace }}
{{- $environment := last $namespaceParts }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:image-puller-vault-sa-{{ $environment }}'
  namespace: {{ .Values.app.licenseplate }}-tools
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.app.licenseplate }}-vault'
    namespace: {{ .Values.app.licenseplate }}-{{ $environment }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'