"""etlruncycle

Revision ID: 07c0dcd415ea
Revises: e817bbaef67e
Create Date: 2022-10-03 16:50:54.900096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c0dcd415ea'
down_revision = 'e817bbaef67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etlruncycle',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('packagename', sa.String(length=100), nullable=True),
                    sa.Column('runcyclestartdatetime', sa.DateTime(), nullable=True),
                    sa.Column('runcycleenddatetime', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.String(length=3000), nullable=True),
                    sa.Column('success', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etlruncycle')
    # ### end Alembic commands ###
