"""add_base_model

Revision ID: 4465a61e851e
Revises: 3e0562c580fe
Create Date: 2022-08-02 17:00:58.786023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4465a61e851e'
down_revision = '3e0562c580fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('active_flag', sa.String(length=1), nullable=True))
    op.alter_column('request_type_radio', 'id', type_=sa.String(length=100), existing_type=sa.INTEGER)
    op.add_column('response_type_radio', sa.Column('request_id', sa.String(length=100), nullable=False))
    op.alter_column('response_type_radio', 'request_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('response_type_radio_engagement_id_fkey', 'response_type_radio', type_='foreignkey')
    op.drop_constraint('response_type_radio_survey_id_fkey', 'response_type_radio', type_='foreignkey')
    op.drop_constraint('response_type_radio_user_id_fkey', 'response_type_radio', type_='foreignkey')
    op.execute('ALTER TABLE response_type_radio DROP CONSTRAINT response_type_radio_pkey CASCADE')
    op.create_foreign_key(None, 'response_type_radio', 'request_type_radio', ['request_id', 'request_key', 'survey_id', 'engagement_id'], ['id', 'key', 'survey_id', 'engagement_id'])
    op.alter_column('response_type_radio', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_type_selectbox', 'id', type_=sa.String(length=100), existing_type=sa.INTEGER)
    op.add_column('response_type_selectbox', sa.Column('request_id', sa.String(length=100), nullable=False))
    op.drop_constraint('response_type_selectbox_survey_id_fkey', 'response_type_selectbox', type_='foreignkey')
    op.drop_constraint('response_type_selectbox_user_id_fkey', 'response_type_selectbox', type_='foreignkey')
    op.drop_constraint('response_type_selectbox_engagement_id_fkey', 'response_type_selectbox', type_='foreignkey')
    op.execute('ALTER TABLE response_type_selectbox DROP CONSTRAINT response_type_selectbox_pkey CASCADE')
    op.create_foreign_key(None, 'response_type_selectbox', 'request_type_selectbox', ['request_id', 'request_key', 'survey_id', 'engagement_id'], ['id', 'key', 'survey_id', 'engagement_id'])
    op.alter_column('response_type_selectbox', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_type_textarea', 'id', type_=sa.String(length=100), existing_type=sa.INTEGER)
    op.add_column('response_type_textarea', sa.Column('request_id', sa.String(length=100), nullable=False))
    op.alter_column('response_type_textarea', 'request_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('response_type_textarea_engagement_id_fkey', 'response_type_textarea', type_='foreignkey')
    op.drop_constraint('response_type_textarea_user_id_fkey', 'response_type_textarea', type_='foreignkey')
    op.drop_constraint('response_type_textarea_survey_id_fkey', 'response_type_textarea', type_='foreignkey')
    op.execute('ALTER TABLE response_type_textarea DROP CONSTRAINT response_type_textarea_pkey CASCADE')
    op.create_foreign_key(None, 'response_type_textarea', 'request_type_textarea', ['request_id', 'request_key', 'survey_id', 'engagement_id'], ['id', 'key', 'survey_id', 'engagement_id'])
    op.alter_column('response_type_textarea', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request_type_textfield', 'id', type_=sa.String(length=100), existing_type=sa.INTEGER)
    op.add_column('response_type_textfield', sa.Column('request_id', sa.String(length=100), nullable=False))
    op.alter_column('response_type_textfield', 'request_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('response_type_textfield_user_id_fkey', 'response_type_textfield', type_='foreignkey')
    op.drop_constraint('response_type_textfield_engagement_id_fkey', 'response_type_textfield', type_='foreignkey')
    op.drop_constraint('response_type_textfield_survey_id_fkey', 'response_type_textfield', type_='foreignkey')
    op.execute('ALTER TABLE response_type_textfield DROP CONSTRAINT response_type_textfield_pkey CASCADE')
    op.create_foreign_key(None, 'response_type_textfield', 'request_type_textfield', ['request_id', 'request_key', 'survey_id', 'engagement_id'], ['id', 'key', 'survey_id', 'engagement_id'])
    op.alter_column('response_type_textfield', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('survey', 'version')
    op.add_column('user', sa.Column('active_flag', sa.String(length=1), nullable=True))
    op.add_column('user_feedback', sa.Column('active_flag', sa.String(length=1), nullable=True))
    op.drop_constraint('user_feedback_user_id_fkey', 'user_feedback', type_='foreignkey')
    op.execute('ALTER TABLE user_feedback DROP CONSTRAINT user_feedback_pkey CASCADE')
    op.create_primary_key('user_feedback_pkey', 'user_feedback', ['id', 'survey_id', 'engagement_id'])
    op.alter_column('user_feedback', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('user_response_detail_user_id_fkey', 'user_response_detail', type_='foreignkey')
    op.execute('ALTER TABLE user_response_detail DROP CONSTRAINT user_response_detail_pkey CASCADE')
    op.create_primary_key('user_response_detail_pkey', 'user_response_detail', ['id', 'survey_id', 'engagement_id'])
    op.alter_column('user_response_detail', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_response_detail_user_id_fkey', 'user_response_detail', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_response_detail', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('user_feedback_user_id_fkey', 'user_feedback', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_feedback', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_feedback', 'active_flag')
    op.drop_column('user', 'active_flag')
    op.add_column('survey', sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'response_type_textfield', type_='foreignkey')
    op.create_foreign_key('response_type_textfield_survey_id_fkey', 'response_type_textfield', 'survey', ['survey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('response_type_textfield_engagement_id_fkey', 'response_type_textfield', 'engagement', ['engagement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('response_type_textfield_user_id_fkey', 'response_type_textfield', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('response_type_textfield', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_type_textfield', 'request_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('response_type_textfield', 'request_id')
    op.drop_constraint(None, 'response_type_textarea', type_='foreignkey')
    op.create_foreign_key('response_type_textarea_survey_id_fkey', 'response_type_textarea', 'survey', ['survey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('response_type_textarea_user_id_fkey', 'response_type_textarea', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('response_type_textarea_engagement_id_fkey', 'response_type_textarea', 'engagement', ['engagement_id'], ['id'], ondelete='CASCADE')
    op.alter_column('response_type_textarea', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_type_textarea', 'request_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('response_type_textarea', 'request_id')
    op.drop_constraint(None, 'response_type_selectbox', type_='foreignkey')
    op.create_foreign_key('response_type_selectbox_engagement_id_fkey', 'response_type_selectbox', 'engagement', ['engagement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('response_type_selectbox_user_id_fkey', 'response_type_selectbox', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('response_type_selectbox_survey_id_fkey', 'response_type_selectbox', 'survey', ['survey_id'], ['id'], ondelete='CASCADE')
    op.alter_column('response_type_selectbox', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('response_type_selectbox', 'request_id')
    op.drop_constraint(None, 'response_type_radio', type_='foreignkey')
    op.create_foreign_key('response_type_radio_user_id_fkey', 'response_type_radio', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('response_type_radio_survey_id_fkey', 'response_type_radio', 'survey', ['survey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('response_type_radio_engagement_id_fkey', 'response_type_radio', 'engagement', ['engagement_id'], ['id'], ondelete='CASCADE')
    op.alter_column('response_type_radio', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_type_radio', 'request_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('response_type_radio', 'request_id')
    op.drop_column('engagement', 'active_flag')
    # ### end Alembic commands ###
