"""ETL Models redone

Revision ID: c03b11293c59
Revises: 
Create Date: 2022-08-16 20:49:33.177210

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c03b11293c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source_engagement_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('start_date', sa.DateTime(), nullable=True),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('published_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('survey',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source_survey_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('engagement_id', sa.Integer(), nullable=True, comment='Source System Engagement Id.MET DB Eng Id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('request_type_radio',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=200), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('request_type_selectbox',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=200), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('request_type_textarea',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=200), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('request_type_textfield',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=200), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('response_type_radio',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('request_key', sa.String(length=100), nullable=False),
                    sa.Column('value', sa.String(length=1000), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'request_key')
                    )
    op.create_table('response_type_selectbox',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('request_key', sa.String(length=100), nullable=False),
                    sa.Column('value', sa.String(length=1000), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'request_key')
                    )
    op.create_table('response_type_textarea',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('request_key', sa.String(length=100), nullable=False),
                    sa.Column('value', sa.String(length=1000), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'request_key')
                    )
    op.create_table('response_type_textfield',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('request_key', sa.String(length=100), nullable=False),
                    sa.Column('value', sa.String(length=1000), nullable=True),
                    sa.Column('request_id', sa.String(length=20), nullable=True),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'request_key')
                    )
    op.create_table('user_feedback',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('comment', sa.String(length=5000), nullable=True),
                    sa.Column('sentiment_analysis', sa.String(length=100), nullable=True),
                    sa.Column('label', sa.String(length=100), nullable=True),
                    sa.Column('source_comment_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', 'survey_id')
                    )
    op.create_table('user_response_detail',
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('survey_id', sa.Integer(), nullable=False),
                    sa.Column('engagement_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_response_detail')
    op.drop_table('user_feedback')
    op.drop_table('response_type_textfield')
    op.drop_table('response_type_textarea')
    op.drop_table('response_type_selectbox')
    op.drop_table('response_type_radio')
    op.drop_table('request_type_textfield')
    op.drop_table('request_type_textarea')
    op.drop_table('request_type_selectbox')
    op.drop_table('request_type_radio')
    op.drop_table('survey')
    op.drop_table('user')
    op.drop_table('engagement')
    # ### end Alembic commands ###
