"""add_sentiment_to_textarea

Revision ID: e817bbaef67e
Revises: fe0a86c0d458
Create Date: 2022-09-15 16:57:11.296144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e817bbaef67e'
down_revision = 'fe0a86c0d458'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('response_type_textarea', sa.Column('sentiment', sa.String(length=50), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_type_textarea', 'sentiment')
    # ### end Alembic commands ###
