"""Added URL path column to feedback table.

Revision ID: 02ff8ecc6b91
Revises: 25e6609cb4db
Create Date: 2023-11-10 10:33:06.780841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02ff8ecc6b91'
down_revision = '25e6609cb4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('submission_path', sa.String()))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'submission_path')
    # ### end Alembic commands ###
