""" Add engagement settings table

Revision ID: 0329d7d10a5f
Revises: df842dc6d0b7
Create Date: 2023-07-21 13:51:38.752604

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0329d7d10a5f'
down_revision = 'df842dc6d0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_settings',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('send_report', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('engagement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagement_settings')
    # ### end Alembic commands ###
