"""

Revision ID: 04e6c48187da
Revises: 31041fb90d53
Create Date: 2023-08-18 12:45:30.620941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04e6c48187da'
down_revision = '31041fb90d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('status', sa.Enum(
        'Unreviewed', 'Archived', name='feedbackstatustype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'status')
    # ### end Alembic commands ###
