"""

Revision ID: 04e6c48187da
Revises: 31041fb90d53
Create Date: 2023-08-18 12:45:30.620941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04e6c48187da'
down_revision = '31041fb90d53'
branch_labels = None
depends_on = None

# Define the Enum type for feedback status
feedback_status_enum = sa.Enum(
    'Unreviewed', 'Archived', name='feedbackstatustype')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the Enum type in the database
    feedback_status_enum.create(op.get_bind())

    op.add_column('feedback', sa.Column('status', sa.Enum(
        'Unreviewed', 'Archived', name='feedbackstatustype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'status')

    # Drop the Enum type from the database
    feedback_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
