"""survey_block

Revision ID: 0d863f773838
Revises: 6764af39864e
Create Date: 2022-12-21 20:23:24.907724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d863f773838'
down_revision = '6764af39864e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_status_block',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('survey_status', sa.Enum('Upcoming', 'Open', 'Closed', name='submissionstatus'), nullable=False),
    sa.Column('block_text', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'survey_status', name='unique_engagement_status_block')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagement_status_block')
    op.execute('DROP TYPE submissionstatus;')
    # ### end Alembic commands ###
