"""add_manage_metadata_role

Revision ID: 1407e0ad88f6
Revises: 614b5376f19c
Create Date: 2024-05-09 20:58:49.586171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1407e0ad88f6'
down_revision = '614b5376f19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO user_role (created_date, updated_date, id, name, description) VALUES ('{0}', '{0}', 38, 'manage_metadata', 'Role to access metadata management')".format(sa.func.now()))
    op.execute("INSERT INTO group_role_mapping (created_date, updated_date, id, role_id, group_id) VALUES ('{0}', '{0}', 60, 38, 1)".format(sa.func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM group_role_mapping WHERE id = 60")
    op.execute("DELETE FROM user_role WHERE id = 38")
    # ### end Alembic commands ###
