"""survey migration

Revision ID: 14c3a9a8b732
Revises: d0f92ae9ba77
Create Date: 2022-07-04 15:44:07.949638

"""
from alembic import op
from sqlalchemy.dialects.postgresql import UUID
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c3a9a8b732'
down_revision = 'd0f92ae9ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    survey_table = op.create_table('survey',
    sa.Column('id', UUID(as_uuid=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('form_json', sa.JSON(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
     
    conn = op.get_bind()

    op.bulk_insert(survey_table, [
        {'id': 1, 'name': 'test', 'form_json': {}, 'created_date': datetime.utcnow(), 'updated_date': datetime.utcnow(),'created_by': 'tester', 'updated_by': 'tester'}
    ])
    
    conn.execute('SELECT setval(\'survey_id_seq\', 1);')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey')
    # ### end Alembic commands ###
