"""survey migration

Revision ID: 14c3a9a8b732
Revises: d0f92ae9ba77
Create Date: 2022-07-04 15:44:07.949638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c3a9a8b732'
down_revision = 'd0f92ae9ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
