"""Add generated document models

Revision ID: 17bae2d586fb
Revises: 904c1ebca3e3
Create Date: 2022-12-27 16:16:50.850377

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '17bae2d586fb'
down_revision = '904c1ebca3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    document_type = op.create_table('generated_document_type',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    document_template = op.create_table('generated_document_template',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('cdogs_hash_code', sa.String(length=64), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['generated_document_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cdogs_hash_code')
    )
    op.drop_index('ix_user_username', table_name='met_users')
    op.create_index(op.f('ix_met_users_username'), 'met_users', ['username'], unique=False)
    
    op.bulk_insert(document_type, [
        {'id': 1, 'name': 'comment_sheet', 'description': 'Comments export for staff', "created_date": datetime.utcnow()}
    ])
    
    op.bulk_insert(document_template, [
        {'id': 1, 'type_id': 1, 'cdogs_hash_code': None, "extension": "xlsx", "created_date": datetime.utcnow()}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_met_users_username'), table_name='met_users')
    op.create_index('ix_user_username', 'met_users', ['username'], unique=False)
    op.drop_table('generated_document_template')
    op.drop_table('generated_document_type')
    # ### end Alembic commands ###
