"""tenant id in user

Revision ID: 196b0abc23b6
Revises: 13985af9eca0
Create Date: 2023-05-23 05:09:51.963357

"""
import sqlalchemy as sa
from alembic import op
from flask import current_app

from met_api.models import Tenant as TenantModel

# revision identifiers, used by Alembic.
revision = '196b0abc23b6'
down_revision = '13985af9eca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('met_users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key('met_users_tenant_fk', 'met_users', 'tenant', ['tenant_id'], ['id'])
    op.execute("commit")

    default_tenant = TenantModel.find_by_short_name(current_app.config.get('DEFAULT_TENANT_SHORT_NAME'))
    default_id = default_tenant.id

    update_stmt = sa.text('UPDATE met_users SET tenant_id = :default_id')
    op.execute(update_stmt.params(default_id=default_id))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('met_users_tenant_fk', 'met_users', type_='foreignkey')
    op.drop_column('met_users', 'tenant_id')
    # ### end Alembic commands ###
