"""

Revision ID: 1c5883959156
Revises: f037908194df
Create Date: 2023-08-29 20:37:58.652800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c5883959156'
down_revision = 'f037908194df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'status',
                    existing_type=postgresql.ENUM(
                        'Unreviewed', 'Archived', name='feedbackstatustype'),
                    nullable=False)
    op.execute('UPDATE "feedback" SET status = \'Unreviewed\'')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'status',
                    existing_type=postgresql.ENUM(
                        'Unreviewed', 'Archived', name='feedbackstatustype'),
                    nullable=True)
    # ### end Alembic commands ###
