"""Alter engagement add created_by upd_by

Revision ID: 2545d45bb29c
Revises: 05d014ff7410
Create Date: 2022-06-24 09:28:59.551336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2545d45bb29c'
down_revision = '05d014ff7410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('engagement', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.execute('UPDATE engagement SET created_by = user_id, updated_by = user_id WHERE created_by IS NULL')
    op.drop_constraint('engagement_user_id_fkey', 'engagement', type_='foreignkey')
    op.alter_column('engagement', 'created_by', nullable=False)
    op.alter_column('engagement', 'updated_by', nullable=False)
    op.drop_column('engagement', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('engagement_user_id_fkey', 'engagement', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('engagement', 'updated_by')
    op.drop_column('engagement', 'created_by')
    # ### end Alembic commands ###
