"""update_report_settings_column

Revision ID: 25e6609cb4db
Revises: d5a6d9bb804b
Create Date: 2023-10-04 15:58:26.818989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25e6609cb4db'
down_revision = 'd5a6d9bb804b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_setting', 'question_id',
               existing_type=sa.String(250),
               type_=sa.Text())
    op.alter_column('report_setting', 'question_key',
               existing_type=sa.String(250),
               type_=sa.Text())
    op.alter_column('report_setting', 'question_type',
               existing_type=sa.String(250),
               type_=sa.Text())
    op.alter_column('report_setting', 'question',
               existing_type=sa.String(250),
               type_=sa.Text())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_setting', 'question_id',
                    type_=sa.String(250))
    op.alter_column('report_setting', 'question_key',
                    type_=sa.String(250))
    op.alter_column('report_setting', 'question_type',
                    type_=sa.String(250))
    op.alter_column('report_setting', 'question',
                    type_=sa.String(250))
    # ### end Alembic commands ###
