"""tenant id in contact

Revision ID: 2b75eb893e6b
Revises: f6f480b5b664
Create Date: 2023-05-07 21:24:21.296063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b75eb893e6b'
down_revision = 'f6f480b5b664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key('contact_tenant_fk', 'contact', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_tenant_fk', 'contact', type_='foreignkey')
    op.drop_column('contact', 'tenant_id')
    # ### end Alembic commands ###
