"""Tenant table update

Revision ID: 2c2ce3421cd6
Revises: 1407e0ad88f6
Create Date: 2024-05-14 11:45:22.800840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2ce3421cd6'
down_revision = '1407e0ad88f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('contact_name', sa.String(length=50), nullable=True, comment='Name of the primary contact'))
    op.add_column('tenant', sa.Column('contact_email', sa.String(length=255), nullable=True, comment='Email of the primary contact'))
    op.add_column('tenant', sa.Column('logo_credit', sa.String(length=60), nullable=True, comment='Hero banner image credit'))
    op.add_column('tenant', sa.Column('logo_description', sa.String(length=80), nullable=True, comment='Hero banner image description'))
    # Set the default values for existing rows
    op.execute('UPDATE tenant SET contact_name = \'Default Contact Name\' WHERE contact_name IS NULL')
    op.execute('UPDATE tenant SET contact_email = \'default@example.com\' WHERE contact_email IS NULL')
    # Remove server_default after setting the default values
    # future inserts into the table do not use these default values
    op.alter_column('tenant', 'contact_name', server_default=None)
    op.alter_column('tenant', 'contact_email', server_default=None)
    # Alter the columns to set them as NOT NULL
    op.alter_column('tenant', 'contact_name', nullable=False)
    op.alter_column('tenant', 'contact_email', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'logo_description')
    op.drop_column('tenant', 'logo_credit')
    op.drop_column('tenant', 'contact_email')
    op.drop_column('tenant', 'contact_name')
    # ### end Alembic commands ###
