""" add versioning to membership table

Revision ID: 31041fb90d53
Revises: e2d5d38220d9
Create Date: 2023-08-09 14:18:45.335397

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '31041fb90d53'
down_revision = 'e2d5d38220d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('membership', sa.Column('is_latest', sa.Boolean(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE membership SET version = 1")
    op.execute("UPDATE membership SET is_latest = TRUE")
    
    # Change columns to non-nullable
    op.alter_column('membership', 'version', nullable=False)
    op.alter_column('membership', 'is_latest', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membership', 'is_latest')
    op.drop_column('membership', 'version')
    # ### end Alembic commands ###
