"""
Add the view_languages role. Also adds it as an ADMIN role.


Revision ID: 5388f257abfb
Revises: 1407e0ad88f6
Create Date: 2024-05-22 14:55:55.334805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5388f257abfb'
down_revision = '1407e0ad88f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO user_role (created_date, updated_date, id, name, description) VALUES ('{0}', '{0}', 39, 'view_languages', 'Role to view languages')".format(sa.func.now()))
    op.execute("INSERT INTO group_role_mapping (created_date, updated_date, id, role_id, group_id) VALUES ('{0}', '{0}', 61, 39, 1)".format(sa.func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM group_role_mapping WHERE id = 61")
    op.execute("DELETE FROM user_role WHERE id = 39")
    # ### end Alembic commands ###
