"""added shapefile

Revision ID: 5423fd515e04
Revises: db3ffa0dd6ad
Create Date: 2023-03-21 10:32:22.728335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5423fd515e04'
down_revision = 'db3ffa0dd6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_map', sa.Column('geojson', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_map', 'geojson')
    # ### end Alembic commands ###
