"""remove obsolete cta_message column from engagement_translation

Revision ID: 58923bf5bda6
Revises: 63890bdab166
Create Date: 2024-09-24 13:00:12.107334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58923bf5bda6'
down_revision = '63890bdab166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_translation', 'cta_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_translation', sa.Column('cta_message', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
