"""add_subscribe_to_project

Revision ID: 5a1258a76598
Revises: 0329d7d10a5f
Create Date: 2023-07-26 11:54:08.922003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a1258a76598'
down_revision = '0329d7d10a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE TYPE subscriptiontype AS ENUM (\'ENGAGEMENT\', \'PROJECT\', \'TENANT\');')    
    op.add_column('subscription', sa.Column('project_id', sa.String(length=50), nullable=True))
    op.add_column('subscription', sa.Column('type', sa.Enum('ENGAGEMENT', 'PROJECT', 'TENANT', name='subscriptiontype'), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'type')
    op.drop_column('subscription', 'project_id')
    op.execute("""DROP TYPE subscriptiontype""")
    # ### end Alembic commands ###
