"""added documents table

Revision ID: 642925969c53
Revises: e37d79be3a05
Create Date: 2022-11-22 21:00:39.487971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642925969c53'
down_revision = 'e37d79be3a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_documents',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True, comment='File or Folder identifier'),
    sa.Column('parent_document_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('modified_by_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['parent_document_id'], ['widget_documents.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_documents')
    # ### end Alembic commands ###
