"""

Revision ID: 6b92cec8c3f6
Revises: 31041fb90d53
Create Date: 2023-08-18 12:09:52.112981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b92cec8c3f6'
down_revision = '31041fb90d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('status', sa.Enum(
        'Public', 'Internal', name='feedbacksourcetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'status')
    # ### end Alembic commands ###
