"""Create widget, widget item, widget type and contact tables

Revision ID: 6ce7831704cb
Revises: ac4a505ed1e3
Create Date: 2022-10-19 17:20:12.126201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce7831704cb'
down_revision = 'ac4a505ed1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True, comment='A biography or short biographical profile of someone.'),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    widget_type_table = op.create_table('widget_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('widget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('widget_type_id', sa.Integer(), nullable=True),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_type_id'], ['widget_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_type_id', 'engagement_id', name='unique_widget_type')
    )
    op.create_table('widget_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('widget_data_id', sa.Integer(), nullable=False, comment='A dynamic foreign key that could be to any table where the widget data is hosted.'),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_data_id', 'widget_id', name='unique_widget_data')
    )    
    op.bulk_insert(widget_type_table, [
        {'id': 1, 'name': 'Who is Listening', 'description': 'Displays contact information for someone who is monitoring the engagement'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_item')
    op.drop_table('widget')
    op.drop_table('widget_type')
    op.drop_table('contact')
    # ### end Alembic commands ###
