"""remove_content_from_engagement

Revision ID: 734f160dd120
Revises: f3842579261c
Create Date: 2024-03-20 21:01:24.327334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '734f160dd120'
down_revision = 'f3842579261c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement', 'content')
    op.drop_column('engagement', 'rich_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('rich_content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('engagement', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
