"""feedback_ratingtype

Revision ID: 7bf7394a517c
Revises: 5423fd515e04
Create Date: 2023-03-24 13:59:02.463795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bf7394a517c'
down_revision = '5423fd515e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'rating', type_=sa.Text())
    op.execute('DROP TYPE ratingtype;')
    op.execute('CREATE TYPE ratingtype AS ENUM (\'VerySatisfied\', \'Satisfied\', \'Neutral\', \'Unsatisfied\', \'VeryUnsatisfied\', \'NONE\');')
    op.alter_column('feedback', 'rating',
               type_=sa.Enum('NONE', 'VerySatisfied', 'Satisfied', 'Neutral', 'Unsatisfied', 'VeryUnsatisfied', name='ratingtype'),
               postgresql_using='rating::ratingtype',
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'rating',
               existing_type=postgresql.ENUM('VerySatisfied', 'Satisfied', 'Neutral', 'Unsatisfied', 'VeryUnsatisfied', name='ratingtype'),
               nullable=False)
    # ### end Alembic commands ###
