"""

Revision ID: 7cb3da03c2a2
Revises: 45f89f245e3d
Create Date: 2023-03-28 09:50:24.225706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cb3da03c2a2'
down_revision = '45f89f245e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_map', sa.Column('file_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_map', 'file_name')
    # ### end Alembic commands ###
