"""Increase submission.rejected_reason_other length

Revision ID: 7da9c7050bff
Revises: 5423fd515e04
Create Date: 2023-03-27 10:40:26.827693

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7da9c7050bff'
down_revision = '5423fd515e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'rejected_reason_other',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'rejected_reason_other',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
