""" Add new document type and template for cac form submission export

Revision ID: 7ebd9ecfccdd
Revises: 3a88de1e3e7f
Create Date: 2023-09-12 14:58:03.712784

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ebd9ecfccdd'
down_revision = '3a88de1e3e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    document_type = sa.Table(
        'generated_document_type',
        sa.MetaData(),
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String),
        sa.Column('created_date', sa.DateTime, default=datetime.utcnow)
    )

    document_template = sa.Table(
        'generated_document_template',
        sa.MetaData(),
        sa.Column('id', sa.Integer),
        sa.Column('type_id', sa.Integer),
        sa.Column('hash_code', sa.String),
        sa.Column('extension', sa.String),
        sa.Column('created_date', sa.DateTime, default=datetime.utcnow)
    )

    op.bulk_insert(document_type, [
        {'id': 2, 'name': 'cac_form_sheet', 'description': 'cac form submission export for staff'}
    ])

    op.bulk_insert(document_template, [
        {'id': 2, 'type_id': 2, 'hash_code': None, "extension": "xlsx"}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM document_type WHERE id = 2')
    op.execute('DELETE FROM document_template WHERE id = 2')
    # ### end Alembic commands ###
