"""Add the map widget

Revision ID: 8595172f9d96
Revises: 3f11e9145a08
Create Date: 2023-03-03 13:42:48.413988

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8595172f9d96'
down_revision = '3f11e9145a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    widget_type_table = sa.table('widget_type',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String))

    op.bulk_insert(widget_type_table, [
        {'id': 6, 'name': 'Map', 'description': 'Display a map that shows the location of the project'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute('DELETE FROM widget_type WHERE id=6')
    # ### end Alembic commands ###
