"""Alter user table add external_id

Revision ID: 8ab640f6e60d
Revises: eef9cc71cca7
Create Date: 2022-06-16 12:32:10.933832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab640f6e60d'
down_revision = 'eef9cc71cca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('external_id', sa.String(length=50), nullable=True))
    op.execute('UPDATE public.user SET external_id = id WHERE external_id IS NULL')
    op.alter_column('user', 'external_id', nullable=False)
    op.create_unique_constraint(None, 'user', ['external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'external_id')
    # ### end Alembic commands ###
