"""empty message

Revision ID: 9536f547cdd5
Revises: f2b3f08c8d60
Create Date: 2022-11-09 09:07:27.443401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9536f547cdd5'
down_revision = 'f2b3f08c8d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_item', sa.Column('sort_index', sa.Integer(), nullable=True, default=1))
    op.execute('UPDATE public.widget_item SET sort_index = 1')
    op.alter_column('widget_item', 'sort_index', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_item', 'sort_index')
    # ### end Alembic commands ###
