"""add feedback source

Revision ID: ac4a505ed1e3
Revises: 224b70277ac4
Create Date: 2022-10-05 13:36:41.944071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4a505ed1e3'
down_revision = '224b70277ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    source = sa.Enum('Public', 'Internal', name='feedbacksourcetype')
    source.create(op.get_bind())
    op.add_column('feedback', sa.Column('source', sa.Enum('Public', 'Internal', name='feedbacksourcetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'source')
    # ### end Alembic commands ###
