"""tracking id for metadata

Revision ID: b1196306955f
Revises: 7ebd9ecfccdd
Create Date: 2023-09-17 22:11:54.456358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1196306955f'
down_revision = '7ebd9ecfccdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_metadata', sa.Column('project_tracking_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_metadata', 'project_tracking_id')
    # ### end Alembic commands ###
