"""report_setting

Revision ID: b3b5c66cea4b
Revises: 88aba309bc23
Create Date: 2023-06-28 12:05:22.187795

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b3b5c66cea4b'
down_revision = '88aba309bc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_setting',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=250), nullable=True),
    sa.Column('question_key', sa.String(length=100), nullable=True),
    sa.Column('question_type', sa.String(length=100), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True,
              comment='Flag to identify if the question needs to be diplayed on the dashboard.'),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('survey', sa.Column('generate_dashboard', sa.Boolean(), nullable=True))
    op.execute('UPDATE survey SET generate_dashboard = True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'generate_dashboard')
    op.drop_table('report_setting')
    # ### end Alembic commands ###
