"""adding_engagement_consent_message

Revision ID: bd0eb0d25caf
Revises: 4114001e1a4c
Create Date: 2024-01-10 12:21:32.781720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd0eb0d25caf'
down_revision = '4114001e1a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('consent_message', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement', 'consent_message')
    # ### end Alembic commands ###
