"""update comment_status status_name column

Revision ID: cb965cb4a3ad
Revises: 8ca063aafc01
Create Date: 2022-08-08 14:48:08.856309

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'cb965cb4a3ad'
down_revision = '8ca063aafc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE comment_status SET status_name = \'Approved\' WHERE id = 2;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE comment_status SET status_name = \'Accepted\' WHERE id = 2;')
    # ### end Alembic commands ###
