"""update_comment_table

Revision ID: cec8d0371f42
Revises: e2625b0d07ab
Create Date: 2024-02-26 16:18:47.917630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cec8d0371f42'
down_revision = 'e2625b0d07ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'component_id',
               existing_type=sa.String(length=10),
               type_=sa.String(length=50))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'component_id',
               existing_type=sa.String(length=50),
               type_=sa.String(length=10))
    # ### end Alembic commands ###
