"""add_proponent_template

Revision ID: d9777850eb98
Revises: 7ebd9ecfccdd
Create Date: 2023-09-17 12:47:48.475329

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9777850eb98'
down_revision = '7ebd9ecfccdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    document_type = sa.Table(
        'generated_document_type',
        sa.MetaData(),
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String),
        sa.Column('created_date', sa.DateTime, default=datetime.utcnow)
    )

    document_template = sa.Table(
        'generated_document_template',
        sa.MetaData(),
        sa.Column('id', sa.Integer),
        sa.Column('type_id', sa.Integer),
        sa.Column('hash_code', sa.String),
        sa.Column('extension', sa.String),
        sa.Column('created_date', sa.DateTime, default=datetime.utcnow)
    )

    op.bulk_insert(document_type, [
        {'id': 3, 'name': 'proponent_comments_sheet', 'description': 'Comments export for proponent'}
    ])

    op.bulk_insert(document_template, [
        {'id': 3, 'type_id': 3, 'hash_code': None, "extension": "xlsx"}
    ])
    op.execute('UPDATE generated_document_template SET hash_code = null where id = 1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM document_type WHERE id = 3')
    op.execute('DELETE FROM document_template WHERE id = 3')
    # ### end Alembic commands ###
