"""Add marker label column instead of description
Revision ID: db3ffa0dd6ad
Revises: be3880132244
Create Date: 2023-03-14 13:14:35.088089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db3ffa0dd6ad'
down_revision = 'be3880132244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_map', sa.Column('marker_label', sa.String(length=30), nullable=True))
    op.drop_column('widget_map', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_map', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('widget_map', 'marker_label')
    # ### end Alembic commands ###
