"""Remove default_value from engagement_metadata_taxa and add unique constraint

Revision ID: dbe023373f4f
Revises: 35124d2e41cb
Create Date: 2024-01-30 17:05:25.313222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbe023373f4f'
down_revision = '35124d2e41cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'engagement_metadata_taxa', ['id'])
    op.drop_column('engagement_metadata_taxa', 'default_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_metadata_taxa', sa.Column(
        'default_value', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'engagement_metadata_taxa', type_='unique')
    # ### end Alembic commands ###
