"""

Revision ID: e3427bc518f5
Revises: 5423fd515e04
Create Date: 2023-03-24 15:58:37.827487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3427bc518f5'
down_revision = '5423fd515e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_map', sa.Column('file_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_map', 'file_name')
    # ### end Alembic commands ###

