"""add_survey_hidden_column

Revision ID: e5d3bbb8d2f0
Revises: 7d8897c412de
Create Date: 2023-04-05 16:47:19.185256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5d3bbb8d2f0'
down_revision = '7d8897c412de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.execute('UPDATE survey SET is_hidden = false')
    op.alter_column('survey', 'is_hidden', nullable=False, server_default=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'is_hidden')
    # ### end Alembic commands ###
