"""remove_phases_widget_type

Revision ID: f0f7eadf3a40
Revises: ae232e299180
Create Date: 2024-05-30 10:26:56.318088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f7eadf3a40'
down_revision = 'ae232e299180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute('DELETE FROM widget WHERE widget_type_id=3')
    conn.execute('DELETE FROM widget_type WHERE id=3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    widget_type_table = sa.table('widget_type',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String))

    op.bulk_insert(widget_type_table, [
        {'id': 3, 'name': 'Phases', 'description': 'Displays information about the engagement phase'}
    ])
    # ### end Alembic commands ###
