""" Initialize user status
P
Revision ID: f40da1b8f3e0
Revises: 31041fb90d53
Create Date: 2023-08-18 09:50:27.567044

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f40da1b8f3e0'
down_revision = '31041fb90d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE staff_users SET status_id = 1")
    op.alter_column('staff_users', 'status_id', nullable=False, server_default='1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_users', 'status_id', nullable=True, server_default=None)
    op.execute("UPDATE staff_users SET status_id = None")
    # ### end Alembic commands ###
