"""add_survey_template_column

Revision ID: f6f480b5b664
Revises: e5d3bbb8d2f0
Create Date: 2023-04-10 15:33:38.529726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6f480b5b664'
down_revision = 'e5d3bbb8d2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('is_template', sa.Boolean(), nullable=True))
    op.execute('UPDATE survey SET is_template = false')
    op.alter_column('survey', 'is_template', nullable=False, server_default=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'is_template')
    # ### end Alembic commands ###
