"""Add metadata filters to the engagement metadata taxa table.

Revision ID: f8bc8ce202f3
Revises: 734f160dd120
Create Date: 2024-03-21 13:02:12.680363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bc8ce202f3'
down_revision = '734f160dd120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_metadata_taxa', sa.Column(
        'filter_type', sa.String(length=64), nullable=True))
    op.add_column('engagement_metadata_taxa', sa.Column(
        'include_freeform', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_metadata_taxa', 'include_freeform')
    op.drop_column('engagement_metadata_taxa', 'filter_type')
    # ### end Alembic commands ###
