"""Survey Migration

Revision ID: fc570c0faace
Revises: d0f92ae9ba77
Create Date: 2022-07-05 12:21:37.175093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc570c0faace'
down_revision = 'd0f92ae9ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('form_json', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_foreign_key('fk_survey_engagement', 'survey', 'engagement', ['engagement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_survey_engagement', 'survey', type_='foreignkey')
    op.drop_table('survey')
    # ### end Alembic commands ###
