"""basemodel column change

Revision ID: fda10461892d
Revises: 0d863f773838
Create Date: 2022-12-22 05:21:58.579344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fda10461892d'
down_revision = '0d863f773838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('engagement', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('engagement', 'created_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('engagement', 'updated_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('user_status', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.drop_column('user_status', 'modified_by_id')
    op.add_column('widget_documents', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.drop_column('widget_documents', 'modified_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_documents', sa.Column('modified_by_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('widget_documents', 'updated_by')
    op.add_column('user_status', sa.Column('modified_by_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user_status', 'updated_by')
    op.alter_column('engagement', 'updated_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('engagement', 'created_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('engagement', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
