environment: prod

site:
  # The URL of the site. This is used to set the REACT_APP_PUBLIC_URL environment variable.
  # Do not include a trailing slash when updating this URL
  url: "https://met-web-demo.apps.gold.devops.gov.bc.ca"

image:
  # The image tag to use for the deployment.
  # Should match a valid image tag in the image repository.
  tag: "prod"