CREATE ROLE engagement WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION
	PASSWORD 'engagement';
CREATE ROLE analytics WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION
	PASSWORD 'analytics';
CREATE ROLE keycloak WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION
	PASSWORD 'keycloak';
CREATE ROLE redash WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION
	PASSWORD 'redash';
CREATE ROLE dagster WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION
	PASSWORD 'dagster';