kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: met-patroni
      app.kubernetes.io/component: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    {{- range .Values.db.allowIngressPodselectors }}
    - podSelector:
        matchLabels:
{{ toYaml . | indent 10 }}
    {{- end }}
