kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ default "postgres" .Values.postgres.nameOverride }}
      cluster-name: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    {{- range .Values.db.allowIngressPodselectors }}
    - podSelector:
        matchLabels:
{{ toYaml . | indent 10 }}
    {{- end }}
