export const WidgetTabValues = {
    WIDGET_OPTIONS: 'WIDGET_OPTIONS',
    WHO_IS_LISTENING_CREATE: 'WHO_IS_LISTENING_CREATE',
    WHO_IS_LISTENING_FORM: 'WHO_IS_LISTENING_FORM',
    DOCUMENT_FORM: 'DOCUMENT_FORM',
};
