kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.app.name }}-backup
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    role: backup
spec:
  replicas: 1
  strategy:
    type: Recreate # Ensures old pods are terminated and release the PVC before new pods are created
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      role: backup
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        role: backup
      annotations:
        image.openshift.io/triggers: >
          [
            {
              "automatic": true,
              "from": {
                "kind": "ImageStreamTag",
                "name": "{{ .Values.backup.image.name }}:{{ .Values.backup.image.tag }}",
                "namespace": "{{ .Values.backup.image.namespace }}"
              },
              "fieldPath": "spec.template.spec.containers[?(name=='{{ .Values.app.name }}-backup')].image"
            }
          ]
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/namespace: {{ .Values.vault.namespace }}
        vault.hashicorp.com/role: {{ .Values.vault.engine }}
        vault.hashicorp.com/auth-path: {{ .Values.vault.authPath }}
        vault.hashicorp.com/agent-inject-secret-met-fider: {{ .Values.vault.engine }}{{ .Values.vault.path }}/met-fider
        vault.hashicorp.com/agent-inject-template-met-fider: |
          {{ `{{- with secret ` }}"{{ .Values.vault.engine }}{{ .Values.vault.path }}/met-fider"{{ ` }}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}='{{ $v }}'
          {{- end }}
          export DATABASE_PASSWORD='{{ index .Data.data "POSTGRESQL_PASSWORD" }}'
          export DATABASE_USER='{{ index .Data.data "POSTGRESQL_USER" }}'
          {{- end }}` }}
    spec:
      serviceAccountName: {{ .Values.app.licenseplate }}-vault
      volumes:
        - name: fider-backup-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-backup
        - name: backup-verification
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-backup-verification
        - name: fider-backup-config-volume
          configMap:
            name: {{ .Values.app.name }}-backup
            items:
              - key: backup.conf
                path: backup.conf
      containers:
        - name: {{ .Values.app.name }}
          {{- with .Values.backup.image }}
          image: "{{ .repository }}/{{ .namespace }}/{{ .name }}:{{ .tag }}"
          {{- end }}
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              . /vault/secrets/met-fider && \
              bash ./backup.sh
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-backup
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeralStorage }}
          volumeMounts:
            - name: fider-backup-pvc
              mountPath: /backups
            - name: backup-verification
              mountPath: /var/lib/pgsql/data
            - name: fider-backup-config-volume
              mountPath: /backup.conf
              subPath: backup.conf
