kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.app.name }}
    # Limits the number (per 3 seconds) of connections from a single IP address, to prevent abuse
    haproxy.router.openshift.io/rate-limit-connections: {{ .Values.app.ratelimits.enabled | quote }}
    haproxy.router.openshift.io/rate-limit-connections.rate-http: "{{ .Values.app.ratelimits.http }}"
    haproxy.router.openshift.io/rate-limit-connections.rate-tcp: "{{ .Values.app.ratelimits.tcp }}"
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  host: {{ .Values.app.name }}.{{ .Values.app.domain }}