kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.app.name }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  host: {{ .Values.app.name }}.{{ .Values.app.domain }}