kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    role: app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: {{ .Values.app.name }}
    role: app
  type: ClusterIP
  sessionAffinity: None