kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  name: {{ .Chart.Name }}
  host: "{{ tpl .Values.hostname .}}"
  path: /
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
    