apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: "{{.Values.ingress.port}}"
    port: {{.Values.ingress.port}}
    targetPort: {{.Values.ingress.port}}
  selector:
    app: {{ .Chart.Name }}-server
