{{/*
This Job runs before the Helm install/upgrade to fetch secrets from Vault
and store them in Kubernetes Secrets that Dagster pods can access.
*/}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app.name }}-vault-sync-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: vault-sync
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 6
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        component: vault-sync
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/namespace: {{ .Values.vault.namespace }}
        vault.hashicorp.com/auth-path: {{ .Values.vault.authPath }}
        vault.hashicorp.com/role: {{ .Values.vault.engine }}
        vault.hashicorp.com/agent-inject-secret-engagement-patroni: {{ .Values.vault.engine }}{{ .Values.vault.path }}/engagement-patroni
        vault.hashicorp.com/agent-inject-template-engagement-patroni: |
          {{ `{{- with secret ` }}"{{ .Values.vault.engine }}{{ .Values.vault.path }}/engagement-patroni"{{ ` }}
          export DAGSTER_USERNAME="{{ index .Data.data "dagster-username" }}"
          export DAGSTER_PASSWORD="{{ index .Data.data "dagster-password" }}"
          export MET_USERNAME="{{ index .Data.data "met-username" }}"
          export MET_PASSWORD="{{ index .Data.data "met-password" }}"
          export APP_DB_NAME="{{ index .Data.data "app-db-name" }}"
          export HOSTNAME="{{ index .Data.data "hostname" }}"
          export ANALYTICS_USERNAME="{{ index .Data.data "analytics-username" }}"
          export ANALYTICS_PASSWORD="{{ index .Data.data "analytics-password" }}"
          {{- end }}` }}
    spec:
      serviceAccountName: {{ .Values.app.licenseplate }}-vault
      restartPolicy: OnFailure
      containers:
      - name: vault-sync
        image: {{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
            ephemeral-storage: 50Mi
          limits:
            cpu: 100m
            memory: 256Mi
            ephemeral-storage: 100Mi
        command:
        - /bin/bash
        - -c
        - |
          set -euo pipefail
          
          echo "=== Vault Secrets Sync Job Started ==="
          echo "Container started at $(date)"
          echo "Current user: $(whoami)"
          echo "Current UID: $(id -u)"
          
          if [ ! -f /vault/secrets/engagement-patroni ]; then
            echo "ERROR: Vault secrets file /vault/secrets/engagement-patroni not found!"
            exit 1
          fi
          echo "Vault secrets file found."
          echo "File size: $(wc -c < /vault/secrets/engagement-patroni) bytes"
          
          echo "Adding Vault secrets..."
          source /vault/secrets/engagement-patroni
          
          echo "Creating/updating Kubernetes secrets..."
          
          # Create main dagster-vault-secrets Secret
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ .Values.app.name }}-vault-secrets
            namespace: {{ .Release.Namespace }}
            labels:
              app: {{ .Values.app.name }}
              app.kubernetes.io/instance: {{ .Release.Name }}
          type: Opaque
          stringData:
            DAGSTER_DB_USER: "${DAGSTER_USERNAME}"
            DAGSTER_DB_PASSWORD: "${DAGSTER_PASSWORD}"
            MET_DB_USER: "${MET_USERNAME}"
            MET_DB_PASSWORD: "${MET_PASSWORD}"
            MET_DB_DB: "${APP_DB_NAME}"
            MET_DB_HOST: "${HOSTNAME}"
            MET_ANALYTICS_DB_USER: "${ANALYTICS_USERNAME}"
            MET_ANALYTICS_DB_PASSWORD: "${ANALYTICS_PASSWORD}"
            MET_ANALYTICS_DB_DB: "${APP_DB_NAME}"
            MET_ANALYTICS_DB_HOST: "${HOSTNAME}"
            DAGSTER_PG_PASSWORD: "${DAGSTER_PASSWORD}"
          EOF
          
          # Also create dagster-postgresql-secret for compatibility with Dagster chart
          # This secret is referenced explicitly by the Dagster chart for DAGSTER_PG_PASSWORD
          # The resource-policy annotation prevents Helm from deleting/recreating this secret
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ .Values.app.name }}-postgresql-secret
            namespace: {{ .Release.Namespace }}
            labels:
              app: {{ .Values.app.name }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              chart: dagster-{{ .Chart.AppVersion }}
            annotations:
              helm.sh/resource-policy: keep
          type: Opaque
          stringData:
            postgresql-password: "${DAGSTER_PASSWORD}"
          EOF
          
          echo "Secrets synced successfully!"
