kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-daemon
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: dagster-daemon
  policyTypes:
  - Ingress
  ingress:
  # Allow from other Dagster components
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Release.Name }}
