apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.name }}-user-deployments-image-puller-{{ .Values.environment }}
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: {{ index .Values.dagster "dagster-user-deployments" "serviceAccount" "name" }}
  namespace: {{ .Release.Namespace }}

