{{/*
This creates a placeholder Secret that will be populated by the vault-sync Job.
The actual secret data is injected by the Job before deployments start.
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-vault-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data: {}
