"""add unique constraint to tenant short_name

Revision ID: ae232e299180
Revises: 2c2ce3421cd6
Create Date: 2024-05-17 15:41:52.346746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae232e299180'
down_revision = '2c2ce3421cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tenant', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant', type_='unique')
    # ### end Alembic commands ###
