"""create_engagement_translation_table

Revision ID: c4f7189494ed
Revises: dbe023373f4f
Create Date: 2024-03-07 16:38:26.958748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4f7189494ed'
down_revision = 'dbe023373f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_translation',
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('engagement_id', sa.Integer(), nullable=False),
                    sa.Column('language_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('rich_description', postgresql.JSON(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('rich_content', postgresql.JSON(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('consent_message', postgresql.JSON(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('slug', sa.String(length=200), nullable=True),
                    sa.Column('upcoming_status_block_text', postgresql.JSON(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('open_status_block_text', postgresql.JSON(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('closed_status_block_text', postgresql.JSON(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('created_by', sa.String(
                        length=50), nullable=True),
                    sa.Column('updated_by', sa.String(
                        length=50), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['language_id'], ['language.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('engagement_id', 'language_id',
                                        name='_engagement_language_uc')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagement_translation')
    # ### end Alembic commands ###
