kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: engagement-pipeline
rules:
  - apiGroups:
    - 'rbac.authorization.k8s.io'
    resources:
    - roles
    - rolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete