{{/*
RoleBinding to allow e903c2-vault ServiceAccount to manage secrets.
This is required for the vault-sync Job to create Secrets from Vault data.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-secret-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: vault-secret-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secret-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: vault-secret-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-secret-manager
subjects:
- kind: ServiceAccount
  name: {{ .Values.app.licenseplate }}-vault
  namespace: {{ .Release.Namespace }}
