kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'engagement-pipeline-edit-binding'
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: 'engagement-pipeline'
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'engagement-pipeline-role-view-binding'
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: 'engagement-pipeline'
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: engagement-pipeline