apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
    app-group: met-app
  name: {{ .Values.app.name }}
spec:
  replicas: 1 # This is managed by the HPA
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        app-group: met-app
        environment: {{ .Values.environment }}
      annotations:
        image.openshift.io/triggers: >
          [
            {
              "automatic": true,
              "from": {
                "kind": "ImageStreamTag",
                "name": "{{ .Values.app.name }}:{{ .Values.image.tag }}",
                "namespace": "{{ .Values.image.namespace }}"
              },
              "fieldPath": "spec.template.spec.containers[?(name=='{{ .Values.app.name }}')].image"
            }
          ]
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}/{{ .Values.app.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}
          resources:
            requests:
              cpu: 150m
              memory: 250Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 300m
              memory: 1Gi
              ephemeral-storage: 2Gi
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30