apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.app.name }}
    app-group: met-app
  name: {{ .Values.app.name }}
spec:
  replicas: 1 # This is managed by the HPA
  revisionHistoryLimit: 10
  selector:
    app: {{ .Values.app.name }}
  strategy:
    activeDeadlineSeconds: 600
    type: Rolling
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        app-group: met-app
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}/{{ .Values.app.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}
          env:
            - name: ENV
              value: {{ .Values.environment | upper }}
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 150m
              memory: 250Mi
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ .Values.app.name }}
        from:
          kind: ImageStreamTag
          name: {{ .Values.app.name }}:{{ .Values.image.tag }}
          namespace: {{ .Values.image.namespace }}