name: Deploy to TEST

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (test/prod)"
        required: true
        default: "test"

defaults:
  run:
    shell: bash
    working-directory: ./openshift

jobs:
  met-deployment:
    runs-on: ubuntu-20.04
    environment: 
      name: test
    steps:
      - uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT_SA_TOKEN}}

      - name: Tag Images and Rollout
        shell: bash
        run: |
          sh deploy.sh ${{ github.event.inputs.environment }}