name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (test/prod)"
        required: true
        default: "test"

defaults:
  run:
    shell: bash
    working-directory: ./openshift

env:
  TAG_NAME: "${{ github.event.inputs.environment || 'test' }}" # If the environment type is manually selected, use the input value; otherwise, use 'test' as default

  OPENSHIFT_LOGIN_REGISTRY: ${{ secrets.OPENSHIFT_LOGIN_REGISTRY }}
  OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
  OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_REPOSITORY }}

jobs:
  met-deployment:
    runs-on: ubuntu-20.04
    environment: 
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{env.OPENSHIFT_LOGIN_REGISTRY}} --token=${{env.OPENSHIFT_SA_TOKEN}}

      - name: Tag Images and Rollout
        shell: bash
        run: |
          sh deploy.sh ${{ github.event.inputs.environment }} ${{env.OPENSHIFT_REPOSITORY }}
