name: MET ETL CD

on:
  push:
    branches:
      - main
    paths:
      - "met-etl/**"
      - "met-api/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

defaults:
  run:
    shell: bash
    working-directory: ./met-etl

env:
  APP_NAME: "dagster-etl"
  DEPLOYMENT_NAME: "dagster-dagster-user-deployments-etl"
  TAG_NAME: "${{ github.event.inputs.environment || 'dev' }}"

  OPENSHIFT_LOGIN_REGISTRY: ${{ secrets.OPENSHIFT_LOGIN_REGISTRY }}
  OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
  OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT_SA_NAME }}
  OPENSHIFT_IMAGE_REGISTRY: ${{ secrets.OPENSHIFT_IMAGE_REGISTRY }}
  OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_REPOSITORY }}

jobs:
  met-etl-cd:
    runs-on: ubuntu-24.04

    if: github.repository == 'bcgov/met-public'
    environment:
      name: "dev"

    steps:
      - uses: actions/checkout@v5

      - name: Install Openshift Tooling
        uses: redhat-actions/openshift-tools-installer@v1.13.1
        with:
          oc: "4.16"

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${OPENSHIFT_LOGIN_REGISTRY} --token=${OPENSHIFT_SA_TOKEN}

      - name: Login Docker
        run: |
          echo "${OPENSHIFT_SA_TOKEN}" | 
          docker login ${OPENSHIFT_IMAGE_REGISTRY} -u ${OPENSHIFT_SA_NAME} --password-stdin

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag image

      - name: Push image
        run: |
          IMAGE_ID=${OPENSHIFT_IMAGE_REGISTRY}/"${OPENSHIFT_REPOSITORY}-tools"/$APP_NAME
          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
          docker image tag $IMAGE_ID:latest $IMAGE_ID:$TAG_NAME
          docker push $IMAGE_ID:$TAG_NAME

      - name: Rollout
        shell: bash
        run: |
          oc rollout status deployment/${DEPLOYMENT_NAME} -n ${OPENSHIFT_REPOSITORY}-${TAG_NAME} -w
