name: MET NOTIFY API CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "notify-api/**"

defaults:
  run:
    shell: bash
    working-directory: ./notify-api

jobs:
  setup-job:
    runs-on: ubuntu-latest

    if: github.repository == 'bcgov/met-public'

    steps:
      - uses: actions/checkout@v3
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
      - name: Lint with pylint
        id: pylint
        run: |
          make pylint
      - name: Lint with flake8
        id: flake8
        run: |
          make flake8

  build-check:
    needs: setup-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build to check strictness
        id: build
        run: |
          make build-nc
