name: ZAP Scanner
on:
  workflow_dispatch:

jobs:
  zap_scan_analytics:
    runs-on: ubuntu-latest
    name: Scan the analytics application
    steps:
      - name: zap_scan_analytics
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Analytics ZAP Scan Report'
          target: 'https://met-analytics-api-dev.apps.gold.devops.gov.bc.ca/'
