name: ZAP Scanner
on:
  workflow_dispatch:

jobs:
  zap_scan_notify:
    runs-on: ubuntu-latest
    name: Scan the notify application
    steps:
      - name: zap_scan_notify
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Notify ZAP Scan Report'
          target: 'https://met-notify-api-dev.apps.gold.devops.gov.bc.ca/'
