name: ZAP Scanner
on:
  workflow_dispatch:

jobs:
  zap_scan_web:
    runs-on: ubuntu-latest
    name: Scan the met application
    steps:
      - name: zap_scan_web
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'WEB ZAP Scan Report'
          target: 'https://met-web-dev.apps.gold.devops.gov.bc.ca/'
