name: ZAP Scanner - MET API
on:
  workflow_dispatch:

jobs:
  zap_scan_api:
    runs-on: ubuntu-latest
    name: Scan the API application
    steps:
      - name: zap_scan_api
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          allow_issue_writing: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'API ZAP Scan Report'
          target: 'https://met-api-dev.apps.gold.devops.gov.bc.ca/'
